# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22eca89b175433bff41be554e3399152bcabd7d8f93444378b3f1682e2e191159bc6124c422ec3670d4c15c3c24283033e4b900ce82ba492a4a6016451edf5fe

test:
  secret_key_base: a81c1a4e947cabcd87dd5f735b3aa5d9386969e3df209ae9425385fab434d23112b821e43167738c94be93bdd184801e1c0a5492237354f2b9886a3eb0451e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
